config/routes.rb
Rails.application.routes.draw do
  root 'pages#home'
  get 'about', to: 'pages#about'

  resources :articles

  resources :categories, except: [:destroy]

  resources :users, except: [:new]

  get 'signup', to: 'users#new'
  get 'login', to: 'sessions#new'
  post 'login', to: 'sessions#create'
  delete 'logout', to: 'sessions#destroy'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/article.rb
class Article < ActiveRecord::Base
  belongs_to :user
  has_many :article_categories
  has_many :categories, through :article_categories
  
  validates :title, presence: true, length: {minimum:3, maximum:50}
  validates :description, presence: true, length: {minimum:10, maximum:500}
  validates :user_id, presence: true
end

app/models/article_category.rb
class ArticleCategory < ActiveRecord::Base
  belongs_to :article
  belongs_to :category
end

app/models/category.rb
class Category < ActiveRecord::Base
  has_many :article_categories
  has_many :articles, through :article_categories

  validates :name,
    presence: true,
    uniqueness: {case_sensitive: false},
    length: {minimum:3, maximum:50}
end

app/models/user.rb
class User < ActiveRecord::Base
  # dependent: :destroy deletes items in db that are related
  has_many :articles, dependent: :destroy

  before_save { self.email = email.downcase }

  validates :username,
    presence: true,
    uniqueness: {case_sensitive: false},
    length: {minimum: 3, maximum: 25}

    VALID_EMAIL_REGEX= /\A[\w+\-.]+@[a-z\d\-]+(\.[a-z]+)*\.[a-z]+\z/i
    validates :email,
      format: {with: VALID_EMAIL_REGEX},
      presence: true,
      uniqueness: {case_sensitive: false},
      length: {maximum: 105}

    has_secure_password
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

  helper_method :current_user, :logged_in?
  def current_user
     @current_user ||= User.find(session[:user_id]) if session[:user_id]
  end

  def logged_in?
    !!current_user
  end

  def require_user
    if !logged_in?
      flash[:danger] = "You must logged in to perforn that action"
      redirect_to root_path
    end
  end
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
  before_action :set_article, only: [:show, :edit, :update, :destroy]
  before_action :require_user, except: [:index, :show]
  before_action :require_same_user, only: [:edit, :update, :destroy]

  def index
    @articles = Article.paginate(page: params[:page], per_page: 5)
  end

  def show
  end

  def new
    @article = Article.new
  end

  def edit
  end

  def create
    # Display the parameters that are send by new
    # render plain: params[:article].inspect

    @article = Article.new(article_params)
    @article.user = current_user

    if @article.save
      flash[:success] = "Article was successfully created!"
      redirect_to article_path(@article)
    else
      render 'new'
    end
  end

  def update
    if @article.update(article_params)
      flash[:success] = "Article was successfully updated!"
      redirect_to article_path(@article)
    else
      render 'edit'
    end
  end

  def destroy
    @article.destroy
    flash[:danger] = "Article was successfully deleted!"
    redirect_to articles_path
  end

  private
  def set_article
    @article = Article.find(params[:id])
  end

  def article_params
    params.required(:article).permit(:title, :description, category_ids:[])
  end

  def require_same_user
    if current_user != @article.user and !current_user.admin?
      flash[:danger] = "Permittion denied."
      redirect_to root_path
    end
  end
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  before_action :set_category, only: [:show, :edit, :update, :destroy]
  before_action :require_admin, except: [:index, :show]

  def index
    @categories = Category.paginate(page: params[:page], per_page: 5)
  end

  def show
    @category_articles = @category.articles.paginate(page: params[:page], per_page: 5)
  end

  def new
    @category = Category.new
  end

  def edit
  end

  def create
    # Display the parameters that are send by new
    # render plain: params[:article].inspect

    @category = Category.new(category_params)

    if @category.save
      flash[:success] = "Category was successfully created!"
      redirect_to category_path(@category)
    else
      render 'new'
    end
  end

  def update
    if @category.update(category_params)
      flash[:success] = "Category was successfully updated!"
      redirect_to category_path(@category)
    else
      render 'edit'
    end
  end

  def destroy
    @category.destroy
    flash[:danger] = "Category was successfully deleted!"
    redirect_to categories_path
  end

  private
  def set_category
    @category = Category.find(params[:id])
  end

  def category_params
    params.required(:category).permit(:name)
  end

  def require_admin
    if !logged_in? || (logged_in? && !current_user.admin?)
      flash[:danger] = "Permittion denied."
      redirect_to root_path
    end
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
    redirect_to articles_path if logged_in?
  end

  def about
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end

  def create
    user = User.find_by(email: params[:session][:email].downcase)
    if user && user.authenticate(params[:session][:password])
      session[:user_id] = user.id
      flash[:success] = "Logged in!"
      redirect_to user_path(user)
    else
      flash.now[:danger] = "Username or password not valid."
      render 'new'
    end
  end

  def destroy
    session[:user_id] = nil
    flash[:success] = "Logged out!"
    redirect_to root_path
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show, :edit, :update]
  before_action :require_same_user, only: [:edit, :update, :destroy]
  before_action :require_admin, only: [:destroy]

  def index
    @users = User.paginate(page: params[:page], per_page: 5)
  end

  def show
    @user_articles = @user.articles.paginate(page: params[:page], per_page: 5)
  end

  def new
    @user = User.new
  end

  def edit
  end

  def create
    @user = User.new(user_params)

    if @user.save
      session[:user_id] = @user.id
      flash[:success] = "User was successfully registered!"
      redirect_to user_path(@user)
    else
      render 'new'
    end
  end

  def update
    if @user.update(user_params)
      flash[:success] = "User Profile was successfully updated!"
      redirect_to edit_user_path
    else
      render 'edit'
    end
  end

  def destroy
    @user.destroy
    flash[:danger] = "User was successfully deleted!"
    redirect_to users_path
  end

  private
  def set_user
    @user = User.find(params[:id])
  end

  def user_params
    params.required(:user).permit(:username, :email, :password)
  end

  def require_same_user
    if current_user != @user and !current_user.admin?
      flash[:danger] = "Permittion denied."
      redirect_to root_path
    end
  end

  def require_admin
    if logged_in? && !current_user.admin?
      flash[:danger] = "Permittion denied."
      redirect_to root_path
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def gravatar_for(user, options = {size: 80})
    gravatar_id = Digest::MD5::hexdigest(user.email.downcase)
    size = options[:size]
    gravatar_url = "https://secure.gravatar.com/avatar/#{gravatar_id}?s=#{size}"
    image_tag(gravatar_url, alt: user.username, class: "img-circle")
  end
end

app/views/articles/_article.html.erb
<% obj.each do |article| %>
  <div class="row">
    <div class="col-xs-8 col-xs-offset-2">
      <div class="well well-lg">
        <h3><%= article.title %></h3>
        <p><%= article.body %></p>
        <hr>
        <small>
          Created at: <%= time_ago_in_words(article.created_at) %> ago<br/>
          Updated at: <%= time_ago_in_words(article.updated_at) %> ago
        </small>
        <hr>
        <% if @article.categories.any? %>
          <p>Categories: <%= render @article.categories %></p>
        <% end %>
        <hr>
        <% if logged_in? && (current_user == article.user || current_user.admin?) %>
          <link_to "Edit", edit_article_path(article), class: "btn btn-primary btn-xs">
          <link_to "Delete", article_path(article), class: "btn btn-primary btn-xs" method: :delete, data: { confirm: "Are you sure?" }>
        <% end %>
      </div>
    </div>
  </div>
<% end %>

app/views/articles/_form.html.erb
<%= render 'partials/errors', obj: @article %>
<div class="row">
  <div class="col-md-12">
    <%= form_for(@article, :html => {class: "form-horizontal", role: "form"}) do |f| %>
      <div class="form-group">
        <div class="control-label col-sm-2">
          <%= f.label :title %>
        </div>
        <div class="col-sm-8">
          <%= f.text_field :title, class: "form-control", placeholder: "Enter Title", autofocus: true %>
        </div>
      </div>
      <div class="form-group">
        <div class="control-label col-sm-2">
          <%= f.label :description %>
        </div>
        <div class="col-sm-10">
          <%= f.text_area :description, class: "form-control", placeholder: "Enter Body of article", rows: 10%>
        </div>
      </div>
      <div class="form-group">
        <div class="control-label col-sm-2">
          <%= f.label :category_id %>
        </div>
        <div class="col-sm-10">
          <%= f.collection_check_boxes :category_ids, Category.all, :id, :name do |cb| %>
            <% cb.label(class: "checkbox-inline input_checkbox") { cb.check_box(class: "checkbox") } %>
          <% end %>
        </div>
      </div>
      <div class="form-group">
        <div class="col-sm-offset-2 col-sm-10">
          <%= f.submit class: 'btn btn-primary btn-lg' %>
          <%= link_to 'Cancel', articles_path, class: 'btn btn-danger btn-lg' %>
        </div>
      </div>
    <% end %>
  </div>
</div>

app/views/articles/edit.html.erb
<h1 align="center">Edit Article</h1>
<%= render 'form'  %>

app/views/articles/index.html.erb
<h1>
  Articles
  <% if logged_in? %>
    <%= link_to 'Create New', new_article_path, class: 'btn btn-success btn-small' %>
  <% end %>
</h1>
<div align="center">
  <%= will_paginate %>
</div>
<%= render 'article', obj: @articles %>
<div align="center">
  <%= will_paginate %>
</div>

app/views/articles/new.html.erb
<h1 align="center">New Article</h1>
<%= render 'form'  %>

app/views/articles/show.html.erb
<h2 align="center"><%= @article.title %></h2>
<div class="row">
  <div class="well col-xs-8 col-xs-offset-2">
    <ul class="list-group">
      <div class="row">
        <div class="col-md-4 col-md-offset-4">
          <li class="list-group-item">Created by:</li>
          <li class="list-group-item"><%= link_to gravatar_for(@article.user), user_path(@article.user) %></li>
          <li class="list-group-item"><%= link_to @article.user.username, user_path(@article.user) %></li>
          <li class="list-group-item">
            <small>
              <%= pluralize(@article.user.articles.count, "article") if @article.user.articles %>
            </small>
          </li>
        </div>
      </div>
    </ul>
    <p><%= simple_format(@article.description) %></p>
    <hr>
    <% if @article.categories.any? %>
      <p>Categories: <%= render @article.categories %></p>
    <% end %>
    <hr>
    <div class="article-actions">
      <% if logged_in? && (current_user == article.user || current_user.admin?) %>
        <%= link_to 'Edit', edit_article_path(@article), class: "btn btn-warning btn-xs" %>
        <%= link_to 'Delete', article_path(@article), class: 'btn btn-danger btn-xs' , method: :delete, data: { confirm: "Are you sure?" } %>
      <% end %>
      <%= link_to 'Articles List', articles_path, class: "btn btn-default btn-xs" %>
    </div>
  </div>
</div>

app/views/categories/_category.html.erb
<span class="badge">
  <%= lik_to category.name, category_path(category) %> &nbsp;
</span>

app/views/categories/_form.html.erb
<%= render 'partials/errors', obj: @category %>
<div class="row">
  <div class="col-md-12">
    <%= form_for(@category, :html => {class: "form-horizontal", role: "form"}) do |f| %>
      <div class="form-group">
        <div class="control-label col-sm-2">
          <%= f.label :name %>
        </div>
        <div class="col-sm-8">
          <%= f.text_field :name, class: "form-control", placeholder: "Enter Name", autofocus: true %>
        </div>
      </div>
      <div class="form-group">
        <div class="col-sm-offset-2 col-sm-10">
          <%= f.submit class: 'btn btn-primary btn-lg' %>
          <%= link_to 'Cancel', categories_path, class: 'btn btn-danger btn-lg' %>
        </div>
      </div>
    <% end %>
  </div>
</div>

app/views/categories/edit.html.erb
<h1 align="center">Edit Category</h1>
<%= render "form" %>

app/views/categories/index.html.erb
<h1>
  Categories
  <% if logged_in? && current_user.admin? %>
    <%= link_to 'Create New', new_category_path, class: 'btn btn-success btn-small' %>
  <% end %>
</h1>
<% @categories.each do |category| %>
  <div class="col-md-3 col-sm-6 col-sx-12">
    <div class="well">
        <h3 align="center"><%= link_to category.name, category_path(category) %></h3>
        <hr>
        <small>
          <%= pluralize(category.articles.count, "article") %>
        </small>
        <hr>
        <% if logged_in? && current_user.admin? %>
            <%= link_to "Edit", edit_category_path(category), class: "btn btn-primary btn-xs" %>
            <%=
              link_to "Delete",
              category_path(category),
              class: "btn btn-danger btn-xs",
              method: :delete, data: { confirn: "Are you sure?" }
            %>
        <% end %>
    </div>
  </div>
<% end %>

app/views/categories/new.html.erb
<h1 align="center">New Category</h1>
<%= render "form" %>

app/views/categories/show.html.erb
<h1 align="center">
  <%= @category.name %>
  <% if logged_in? && current_user.admin? %>
    <%= link_to "Edit", edit_category_path(@category), class: "btn btn-primary btn-lg" %>
  <% end %>
</h1>
<hr>
<h4 align="center"><%= @category.name %> articles</h4>
<div class="center">
  <%= will_paginate @category_articles %>
</div>
<%= render 'articles/article', obj: @category_articles %>
<div class="center">
    <%= will_paginate @category_articles %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Alpha Blog</title>
    <%= csrf_meta_tags %>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>
  <body>
  <%= render 'partials/navigation' %>
  <%= render 'partials/messages' %>
    <div class="container">
      <%= yield %>
    </div>
    <%= render 'partials/footer' %>
    <%= debug(params) if Rails.env.development? %>
  </body>
</html>

app/views/pages/about.html.erb
<h1>About</h1>

<%= link_to 'Home', root_path %>

app/views/pages/home.html.erb
<div class="center jumbotron">
  <h1>Alpha Blog</h1>
  <p>...</p>
  <p><%= link_to "Sign up now", signup_path, class: "btn btn-primary btn-lg btn-xl" %></p>
</div>

app/views/partials/_errors.html.erb
<% if obj.errors.any? %>
  <div class="row">
    <div class="col-xs-8 col-xs-offset-2">
      <div class="alert alert-danger">
        <h2>
          <%= pluralize(obj.errors.count, "error") %>
          Article creation failed
        </h2>
        <ul>
          <% obj.errors.full_messages.each do |msg| %>
              <li><%= msg %></li>
          <% end %>
        </ul>  
      </div>
    </div>
  </div>
<% end %>

app/views/partials/_footer.html.erb
<div class="container">
  <footer>
    <small>Copyright &copy; <a href="#">CrikoC</a></small>
    <nav>
      <ul>
        <li><%= link_to 'home', root_path %></li>
        <li><%= link_to 'About', about_path %></li>
        <li><%= link_to 'Articles', articles_path %></li>
      </ul>
    </nav>
  </footer>
</div>

app/views/partials/_messages.html.erb
<div class="row">
  <div class="col-xs-10 col-xs-offset-1">
    <% flash.each do |name, msg| %>
      <div class='alert alert-<%="#{name}" %>'>
        <a href="#" class="close" data-dismiss="alert">&#215;</a>
        <%= content_tag :div, msg, :id => "flash_#{name}" if msg.is_a?(String) %>
      </div>
    <% end %>
  </div>
</div>

app/views/partials/_navigation.html.erb
<nav class="navbar navbar-default">
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <%= link_to 'Alpha Blog', root_path, class: "navbar-brand", id: "logo" %>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav">
        <li><%= link_to "About", about_path %></li>
        <li><%= link_to "Articles", articles_path %></li>
        <li class="dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">
            Categories <span class="caret"></span>
          </a>
          <ul class="dropdown-menu">
            <li><%= link_to "View all", categories_path %></li>
            <li role="separator" class="divider"></li>
            <% @categories.each do |category| %>
              <li><%= link_to category.name, category_path(category) %></li>
            <% end %>
          </ul>
        </li>
        <li><%= link_to "Users", users_path %></li>
      </ul>
      <form class="navbar-form navbar-left">
        <div class="form-group">
          <input type="text" class="form-control" placeholder="Search">
        </div>
        <button type="submit" class="btn btn-default">Submit</button>
      </form>
      <ul class="nav navbar-nav navbar-right">
        <% if !logged_in? %>
          <li><%= link_to "Login", login_path %></li>
          <li><%= link_to "Sign up", signup_path %></li>
        <% else %>
          <li class="dropdown">
            <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">
              <%= current_user.username %> <%= "Admin" if current_user.admin? %> <span class="caret"></span>
            </a>
            <ul class="dropdown-menu">
              <li><%= link_to "View profile", user_path(current_user) %></li>
              <li><%= link_to "Settings", edit_user_path(current_user) %></li>
              <li role="separator" class="divider"></li>
              <li><%= link_to "Logout", logout_path, method: :delete %></li>
              <li role="separator" class="divider"></li>
            </ul>
          </li>
        <% end %>
      </ul>
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>

app/views/users/_form.html.erb
<%= render 'partials/errors', obj: @user %>
<div class="row">
  <div class="col-md-12">
    <%= form_for(@user, :html => {class: "form-horizontal", role: "form"}) do |f| %>
      <div class="form-group">
        <div class="control-label col-sm-2">
          <%= f.label :username %>
        </div>
        <div class="col-sm-8">
          <%= f.text_field :username, class: "form-control", placeholder: "Enter Username", autofocus: true %>
        </div>
      </div>
      <div class="form-group">
        <div class="control-label col-sm-2">
          <%= f.label :email %>
        </div>
        <div class="col-sm-8">
          <%= f.email_field :email, class: "form-control", placeholder: "you@example.com", autofocus: true %>
        </div>
      </div>
      <div class="form-group">
        <div class="control-label col-sm-2">
          <%= f.label :password %>
        </div>
        <div class="col-sm-8">
          <%= f.password_field :password, class: "form-control", placeholder: "Enter Password", autofocus: true %>
        </div>
      </div>
      <div class="form-group">
        <div class="col-sm-offset-2 col-sm-10">
          <%= f.submit class: 'btn btn-primary btn-lg' %>
          <%= link_to 'Cancel', users_path, class: 'btn btn-danger btn-lg' %>
        </div>
      </div>
    <% end %>
  </div>
</div>

app/views/users/edit.html.erb
<h1 align="center">
  Edit User Profile
</h1>
<%= render 'form' %>

app/views/users/index.html.erb
<h1 align="center">Alpha Bloggers</h1>
<div align="center">
  <%= will_paginate %>
</div>
<div class="row">
</div>
<% @users.each do |user| %>
  <div class="col-md-3 col-sm-6 col-sx-12">
    <ul class="list-group">
      <div class="well">
        <li class="list-group-item"><%= link_to gravatar_for(user), user_path(user) %></li>
        <li class="list-group-item"><%= link_to user.username, user_path(user) %></li>
        <li class="list-group-item">
          <small>
            <%= pluralize(user.articles.count, "article") if user.articles %>
          </small>
        </li>
        <% if logged_in? and current_user.admin? %>
          <li class="list-group-item">
            <%=
              link_to "Delete user",
              user_path(user),
              class: "btn btn-danger btn-small",
              method: :delete, data: { confirn: "Are you sure?" }
            %>
          </li>
        <% end %>
      </div>
    </ul>
  </div>
<% end %>
<div align="center">
  <%= will_paginate %>
</div>

app/views/users/new.html.erb
<h1 align="center">
  Sign Up
</h1>
<%= render 'form' %>

app/views/users/show.html.erb
<h1 align="center">Welcome to <%= @user.username %>'s Page</h2>
<div class="row">
  <div class="col-md-4 col-md-offset-4 center">
    <%= gravatar_for @user, size: 150 %>
  </div>
</div>
<h4 align="center"><%= @user.username %>'s articles</h4>
<div class="center">
  <%= will_paginate @user_articles %>
</div>
<%= render 'articles/article', obj: @user_articles %>
<div class="center">
  <%= will_paginate @user_articles %>
</div>